USE JESAL;

-- 1
SELECT * FROM WORKER ORDER BY FIRST_NAME ASC, DEPARTMENT DESC ;

-- 2
SELECT * FROM WORKER WHERE FIRST_NAME IN("VIPUL", "SATISH" ) ;

-- 3
SELECT * FROM worker WHERE FIRST_NAME LIKE "_____%" ;
SELECT * FROM worker WHERE FIRST_NAME LIKE "_____h%" ;

SELECT * FROM WORKER WHERE FIRST_NAME IN ("VIPUL" , "SATISH") ;

SELECT * FROM WORKER WHERE FIRST_NAME IN ("VIPUL" , "SATISH") ;

-- 4
SELECT * FROM WORKER WHERE SALARY < 100000 ;

-- 5
SELECT * FROM WORKER INNER JOIN WORKER_2 ON WORKER.FIRST_NAME=WORKER_2.W_NAME ;

-- 6 
SELECT * FROM WORKER LIMIT 6 ;

-- 7
SELECT * FROM WORKER WHERE PEOPLE < 5 ;

-- 8
SELECT SUM( PEOPLE), DEPARTMENT FROM WORKER GROUP BY DEPARTMENT ;

-- 9
SELECT MAX(SALARY),DEPARTMENT FROM WORKER GROUP BY DEPARTMENT ;

USE JESAL;

CREATE TABLE WORKER_2
( ID INT primary KEY,
W_NAME varchar(34),
SALARY INT ) ;


SELECT * FROM WORKER INNER JOIN WORKER_2 ON WORKER.FIRST_NAME=WORKER_2.W_NAME ;
