USE HR ; 
-- 1
SELECT EMP_FNAM,EMP_LNAME,H_DATE FROM EMP ; 

-- 2
SELECT H_DATE,EMP_FNAM,EMP_LNAME , DEPARTMENT, DESIGNATION FROM EMP WHERE DESIGNATION= "ADMIN" ;

-- 3 
select concat(EMP_ID, ", " , EMP_FNAM) as  Emplee_Title from emp ;

-- 4
SELECT EMP_FNAM,EMP_LNAME,SALARY FROM EMP WHERE SALARY > 2000 ;

-- 5
select concat(EMP_ID,"," , EMP_FNAM,"," ,EMP_LNAME,"," , H_DATE,"," , S_DATE,"," , DESIGNATION,",", SALARY, "," , COMMISSION,
"," , DEPARTMENT,",", DEP_ID, ",",MANAGER) as  output from emp;

-- 6
SELECT EMP_LNAME AS  NAME , S_DATE AS STARTDATE FROM EMP ;

-- 7
SELECT EMP_FNAM,EMP_LNAME,H_DATE FROM EMP ORDER BY H_DATE ;

-- 8
SELECT EMP_FNAM,EMP_LNAME,SALARY FROM EMP ORDER BY SALARY DESC ;

-- 9
SELECT EMP_FNAM AS  ENAME , DEPARTMENT AS  DEPNO FROM EMP WHERE COMMISSION IS NOT NULL  ORDER BY SALARY DESC ;

-- 10
SELECT EMP_FNAM AS  ENAME , DEPARTMENT AS  DEPNO,COMMISSION , SALARY   FROM EMP
 WHERE COMMISSION IS NOT NULL  ORDER BY SALARY DESC ;
 
 -- 11
 SELECT EMP_FNAM, EMP_LNAME, DESIGNATION FROM EMP WHERE NOT DESIGNATION = "ADMIN" ;
 
 -- 12
SELECT EMP_FNAM, EMP_LNAME, DESIGNATION, SALARY FROM EMP WHERE DESIGNATION = WORKER OR CLERK AND SALARY <> 2500 ;
SELECT EMP_FNAM, EMP_LNAME, DESIGNATION, SALARY FROM EMP WHERE DESIGNATION = "WORKER" OR "CLERK" AND SALARY <> 3500;
SELECT EMP_FNAM, EMP_LNAME, DESIGNATION, SALARY FROM EMP WHERE DESIGNATION = "WORKER" OR "CLERK" AND SALARY <> 5000;

  
 