USE HR;

-- 1
SELECT EMP_LNAME,DEPARTMENT,DEP_ID FROM EMP ;

-- 2
SELECT DESIGNATION, DEP_ID, LOCATION FROM EMP WHERE DEP_ID = "AS" ;

-- 3
SELECT EMP_LNAME, DEPARTMENT,DEP_ID, LOCATION ,COMMISSION FROM EMP WHERE COMMISSION > 0 ;

-- 4
SELECT EMP_LNAME , DEPARTMENT FROM EMP WHERE EMP_LNAME LIKE "%a" ;

-- 5
SELECT EMP_LNAME , DESIGNATION, DEP_ID , DEPARTMENT FROM EMP WHERE LOCATION = "AHMEDABAD" ;

-- 6
SELECT EMP_LNAME, EMP_NO , MANAGER , MANAGER_NO FROM EMP ;

-- 7,
SELECT EMP_LNAME, EMP_NO , MANAGER , MANAGER_NO FROM EMP ;

-- 8
SELECT EMP_LNAME, DEP_ID , DEPARTMENT  FROM EMP group by DEPARTMENT ;

-- 9
SELECT EMP_FNAM, EMP_LNAME, DESIGNATION, SALARY, CASE WHEN SALARY >= 5000 THEN 'A' WHEN SALARY >= 3000 THEN 'B' 
WHEN SALARY < 3000 THEN 'C' END AS  GRADE FROM EMP ;
 
-- 10
SELECT concat(EMP_FNAM, ",", H_DATE, ",", MANAGER, ",", MANAGER_HDATE)   from emp 
where  MANAGER_HDATE < H_DATE ;




